name: Build & deploy spring app

on: 
  push:
    branches:
      - main


jobs:
  build-deploy:
    name: build and deploy spring boot for beginners
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: setup JDK17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      
      - name: Unit testss
        run: mvn -B test --file pom.xml

      
      - name: Build the application 
        run: |
          mvn clean 
          mvn -B package --file pom.xml

      - name: Build docker image
        uses: actions/build-push-actions@v2
        with: 
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-boot-for-beginners:$(date-'%Y-%m-%d%H-%M-%S')

      -  name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} 

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:$(date-'%Y-%m-%d%H-%M-%S')
      
